%%% Go to the base folder of the project and add all subfolders to MATLABs
%%%  search path
cd(basefolder)
addpath(genpath(basefolder))


%%% List of scripts by categories and fast way to open them.
% Preparation
a = {'Prepare_Heading_Space.m',...
  'Prepare_Lense_Data.m',...
  'Prepare_Pre_Grids.m',...
  };
cellfun(@open,a)

% Functions
a = {'Stretch_Matrix.m',...
  'Calculate_Spatial_Coefficients.m',...
  'Flowfield_Calculation.m',...
  'Calculate_Orthogonal_Complements.m',...
  'Evaluate_Flowfields.m',...
  'Process_Estimates.m',...
  };
cellfun(@open,a)


% Simulation
a = {'Simulation_Settings.m',...
  'Simulation_of_Movement.m',...
  'Simulation_of_Heading_Estimation.m',...
  };


% Plots
a = {'Plot_Barplot.m',...
  };
